name: diacritics_remover
description: >
    Removes common accents and diacritical signs from a
    string by replacing them with an equivalent character.
version: 0.0.1

homepage: https://github.com/agilord/diacritic

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
